FROM hypriot/rpi-java

ADD target/eightballapi-0.0.1-SNAPSHOT.jar /opt/eightballapi-0.0.1-SNAPSHOT.jar

EXPOSE 7000

ARG EIGHTBALL_DB_URL
ARG EIGHTBALL_DB_USER
ARG EIGHTBALL_DB_PASSWORD
ARG EIGHTBALL_API_KEY

ENV EIGHTBALL_DB_URL=$EIGHTBALL_DB_URL
ENV EIGHTBALL_DB_USER=$EIGHTBALL_DB_USER
ENV EIGHTBALL_DB_PASSWORD=$EIGHTBALL_DB_PASSWORD
ENV EIGHTBALL_API_KEY=$EIGHTBALL_API_KEY

ENTRYPOINT ["java", "-jar", "/opt/eightballapi-0.0.1-SNAPSHOT.jar"]
